
# Imports
from stewbeet import *  # type: ignore


# Main entry point
def main():

    # Add wiki buttons to steel ingot (generated by ores.py)
    obj = Item.from_id("steel_ingot")   # Equivalent to Mem.definitions["steel_ingot"]
    obj.wiki_buttons = [
        WikiButton([
            {"text":"Here is an example of a wiki component,\nthis text component will be displayed as a button in the manual."},
            {"text":"\nYou can write anything you want here.","color":"yellow"},
        ]),
        WikiButton({"text":"This is another button with a simple text component.","color":"aqua"}),
    ]

    # Add a super stone block that can be crafted with 9 deepslate or stone, and has cobblestone as base block
    Block(
        id="super_stone",
        vanilla_block=VanillaBlock(id="minecraft:cobblestone"),
        recipes=[
            # Examples of crafting recipes (shaped and shapeless), no need to specify result -> will default to the Item id
            CraftingShapedRecipe(category="blocks", shape=["XXX","XXX","XXX"], ingredients={"X": Ingr("minecraft:stone")}),
            CraftingShapelessRecipe(category="blocks", ingredients=9*[Ingr("minecraft:deepslate")]),

            # Example of recipe with vanilla result (not custom item)
            SmeltingRecipe(experience=0.1, cookingtime=200, category="blocks", ingredient=Ingr("super_stone"), result=Ingr("minecraft:diamond")),
            BlastingRecipe(experience=0.1, cookingtime=100, category="blocks", ingredient=Ingr("super_stone"), result=Ingr("minecraft:diamond")),
        ],
    )

    # Example of a custom painting
    Painting(
        id="stewbeet_painting",
        painting_data=PaintingData(
            texture="stewbeet_painting_2x2",            # Default to item id if not given (this example links to "assets/textures/stewbeet_painting_2x2.png")
            author={"text":"Stoupy","color":"yellow"},  # Author defaults to ctx.project_author if not given
            title={"text":"Da' Icon","color":"gray"},   # Title defaults to item name if not given
            width=2, height=2
        ),
        recipes=[
            CraftingShapedRecipe(category="decorations", shape=["###","#F#","###"], ingredients={"#":Ingr("#minecraft:eggs"),"F":Ingr("minecraft:beetroot")}),
        ]
    )

    # Add a recipe for the future generated manual (the manual recipe will show up in itself)
    Item(
        id="manual",
        manual_category="miscellaneous",
        recipes=[
            # Put a book and a steel ingot in the crafting grid to get the manual
            CraftingShapelessRecipe(category="misc", ingredients=[Ingr("minecraft:book"), Ingr("steel_ingot")]),

            # Put the manual in the crafting grid to get the manual back (update the manual)
            CraftingShapelessRecipe(category="misc", ingredients=[Ingr("manual")]),
        ],
        components={
            # Set the item name from the beet.yml metadata if available, otherwise default to "Manual"
            "item_name": Mem.ctx.meta.get("stewbeet", {}).get("manual", {}).get("name") or "Manual",
        }
    )

    # ── VanillaBlock use-case test blocks ─────────────────────────────────────

    # Case 1 - No facing at all: block and item_display use default orientation.
    Block(
        id="vb_no_facing",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(id="minecraft:cobblestone"),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:cobblestone")])],
    )

    # Case 2 - Visual-only rotation: item_display rotates with the player (4 horizontal dirs),
    #          but the underlying vanilla block is placed without a facing blockstate.
    Block(
        id="vb_visual_facing",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(id="minecraft:glass", visual_facing_source="player"),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:glass")])],
    )

    # Case 3 - Block + visual rotation: the vanilla block gets a facing= blockstate AND
    #          the item_display rotates (implicit visual_facing_source="player").
    Block(
        id="vb_block_facing",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(id="minecraft:furnace", block_facing="player"),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:furnace")])],
    )

    # Case 4 - Block + visual rotation WITH extra blockstates: the plugin must preserve
    #          the "lit=false" state while still appending "facing=<dir>".
    Block(
        id="vb_block_states",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(id="minecraft:furnace[lit=false]", block_facing="player"),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:furnace"), Ingr("minecraft:coal")])],
    )

    # Case 5 - Contents with native item_frame facing (6 directions from the frame's Facing NBT).
    BlockAlternative(
        id="vb_contents",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(contents=True),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:item_frame")])],
    )

    # Case 6 - Contents with player-overridden facing: get_rotation is called while
    #          @s=player in the search function, then ItemRotation is applied (4 dirs).
    BlockAlternative(
        id="vb_contents_player",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(contents=True, visual_facing_source="player"),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:item_frame"), Ingr("minecraft:compass")])],
    )

    # Case 7 - Contents with explicit item_frame facing (6 directions, same underlying
    #          behaviour as Case 5 but uses the "item_frame" value explicitly).
    BlockAlternative(
        id="vb_contents_frame",
        manual_category="miscellaneous",
        vanilla_block=VanillaBlock(contents=True, visual_facing_source="item_frame"),
        recipes=[CraftingShapelessRecipe(category="blocks", ingredients=[Ingr("minecraft:item_frame"), Ingr("minecraft:string")])],
    )


