"""
This script is called when a Bookshelf release is triggered on GitHub.

It updates the "bookshelf.py" file with the new version information so that
the dynamic download manager can fetch the correct per-module zips from the
Smithed API at build time.  Zip files are no longer stored in this repo.
"""
# Imports
import os
import re
from copy import deepcopy

import requests
import stouputils as stp
from stouputils.typing import JsonDict

# Constants
ROOT: str = stp.get_root_path(__file__, go_up=1)
GITHUB_REPO: str = "https://github.com/mcbookshelf/bookshelf/releases"
API_URL: str = "https://api.github.com/repos/mcbookshelf/bookshelf/releases"
DESTINATION_FOLDER: str = f"{ROOT}/stewbeet/dependencies"
CONFIG_PATH: str = f"{DESTINATION_FOLDER}/bookshelf_config.json"
DEPS_TO_UPDATE: str = "stewbeet/dependencies/bookshelf.py"
MODULE_TEMPLATE: JsonDict = {"version": [0, 0, 0], "name": "Title Name", "url": GITHUB_REPO, "is_used": False}


# Helper function to parse version string (e.g., "v1.2.3" or "1.2.3")
def parse_version(tag: str) -> list[int]:
	tag = tag.lstrip("v")
	return [int(part) for part in tag.split(".") if part.isdigit()]

# Convert PascalCase or dash-style module names to title format
def format_module_name(module: str) -> str:
	# Remove version suffix and minecraft version (e.g., "26.1", "1.21.5")
	module = module.split('-', 1)[0]  # Remove any remaining suffix after the first dash
	# Replace dash/underscore with space, capitalize each word
	return "Bookshelf " + " ".join(word.capitalize() for word in re.split(r"[-_.]", module) if word != "bs")

# Convert PascalCase to snake_case
def pascal_to_snake(name: str) -> str:
	return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

@stp.handle_error
@stp.measure_time
def download_latest_release() -> None:
	"""
	Download the wanted files from the latest release on GitHub.

	Then, generate a new "bookshelf.py" file with the new modules looking like the following:

	BOOKSHELF_MODULES: dict[str, dict] = {
		"bs.block_barrel":    { ... },
		"bs.item_tool":       { ... },
		...
	}
	"""
	stp.info(f"Fetching latest release from {API_URL}")
	response: requests.Response = requests.get(API_URL)
	if response.status_code != 200:
		stp.info(f"Error fetching release info: {response.status_code}")
		return
	releases: list[JsonDict] = response.json()
	if not releases:
		stp.info("No releases found")
		return

	release_info: JsonDict = releases[0]
	tag_name: str = release_info.get("tag_name", "v0.0.0")
	stp.info(f"Latest release tag: {tag_name}")

	modules: dict[str, JsonDict] = {}
	assets: list[JsonDict] = release_info.get("assets", [])

	# Filter assets to only Bookshelf module zips
	assets = [asset for asset in assets if re.match(r"^bs\..*\.zip$", asset.get("name", ""))]

	def extract_module_info(asset: JsonDict) -> tuple[str, JsonDict] | None:
		file_name: str = asset.get("name", "")
		no_extension: str = os.path.splitext(file_name)[0]
		module_name: str = format_module_name(no_extension)
		if not module_name:
			return None

		# Extract module version from name (e.g. "bs.health-1.21.5-v3.0.0.zip" -> [3, 0, 0])
		version: list[int] = parse_version(no_extension.split('-')[-1])

		# Prepare module info
		module_key_snake: str = file_name.split('-')[0]
		module_info: JsonDict = deepcopy(MODULE_TEMPLATE)
		module_info["version"] = version
		module_info["name"] = module_name
		return module_key_snake, module_info

	# Build module dict (no multithreading needed - no downloads)
	results: list[tuple[str, JsonDict]] = [
		x for x in [extract_module_info(a) for a in assets]
		if x is not None
	]
	modules = dict(sorted(results, key=lambda x: x[0]))

	dumped: str = stp.json_dump(modules, max_level=1).replace("false", "False").replace("true", "True")
	file_content: str = f"""
# Imports
from stouputils.typing import JsonDict

# This file is auto-generated by the release script (python_package/scripts/on_bookshelf_release.py).
# Do not edit this file manually.
BOOKSHELF_MODULES: dict[str, JsonDict] = {dumped}
"""

	with open(f"{ROOT}/{DEPS_TO_UPDATE}", "w") as f:
		f.write(file_content)
	stp.info(f"Updated '{DEPS_TO_UPDATE}' with new module information.")

	# Update the config file
	if tag_name != "nightly":
		stp.json_dump({"version": tag_name}, CONFIG_PATH)
	stp.info(f"Updated '{CONFIG_PATH}' with new version information.")

# Main
if __name__ == "__main__":
	download_latest_release()

