import type { Language } from '../context/LanguageContext';

export const translations = {
    en: {
        // Navbar
        nav: {
            features: 'Features',
            installation: 'Installation',
            templates: 'Templates',
            plugins: 'Plugins',
            documentation: 'Documentation',
            github: 'GitHub',
            language: 'Language',
        },
        
        // Hero Section
        hero: {
            title: 'StewBeet',
            subtitle: 'A powerful Python plugin for Beet, supercharging your Minecraft datapack development',
            getStarted: 'Get Started',
            viewDocs: 'View Documentation',
            scrollDown: 'Scroll to explore',
            versionStable: 'Stable Release',
            automateTitle: 'Automate your',
            minecraftDatapacks: 'Minecraft Datapacks',
            description: 'StewBeet is a',
            beet: 'Beet',
            descriptionContinued: 'framework providing powerful automation for Minecraft datapacks. Adaptable to any workflow—use only the features you need, or leverage the full suite for complete project generation.',
            typeSafe: 'Type-safe definitions',
            autoGenerated: 'Auto-generated assets',
            buildTime: 'Build Time',
            fast: 'Fast',
            filesGenerated: 'Files Generated',
        },
        
        // What is StewBeet
        whatIs: {
            title: 'What is StewBeet?',
            description: 'A Beet framework that revolutionizes Minecraft datapack creation by automating everything repetitive and time-consuming.',
            problem: 'The Problem',
            problemDesc: 'Creating a datapack requires manually writing hundreds of JSON files, models, textures, functions...',
            solution: 'The Solution',
            solutionDesc: 'StewBeet automates EVERYTHING: resource pack generation, models, custom blocks, recipes, and much more!',
            result: 'The Result',
            resultDesc: 'Focus on creation, not files. Define your items and let StewBeet generate the rest.',
        },
        
        // Features
        features: {
            title: 'Powerful',
            titleHighlight: 'Automation',
            subtitle: 'StewBeet handles the repetitive parts of datapack creation so you can focus on the mechanics.',
            integrations: 'Integrations',
            // Individual features
            itemModelsTitle: 'Auto Item Models',
            itemModelsDesc: 'Automatically generates item and block models from texture patterns. Detects cube, cake, orientable patterns and more. Recognizes _on suffix to create powered/unpowered state models.',
            loadingTitle: 'Datapack Loading',
            loadingDesc: 'Sets up timing infrastructure with tick, second, minute functions. Includes version checking and LanternLoad compatibility.',
            lootTablesTitle: 'Loot Tables & Give',
            lootTablesDesc: 'Auto-generated loot tables for every defined item along with a convenient _give_all function for testing.',
            manualTitle: 'In-Game Manual',
            manualDesc: 'Automatically generated interactive manual with item documentation, crafting recipes, and clickable navigation.',
            langTitle: 'Auto Lang Files',
            langDesc: 'Automatically extracts text components from your code and generates en_us.json translation files.',
            customBlocksTitle: 'Custom Blocks',
            customBlocksDesc: 'Full custom block system with placement, destruction, ore drops (fortune/silk touch), and Smithed integration.',
        },
        
        // Installation
        installation: {
            title: 'Get Started in',
            titleHighlight: 'Seconds',
            step1: 'Install Python',
            step1Desc: 'Ensure Python 3.14+ is installed',
            step2: 'Install StewBeet',
            step2Desc: 'Get the package via pip',
            step3: 'Initialize Project',
            step3Desc: 'Choose a template to start',
            step4: 'Build',
            step4Desc: 'Generate your datapack',
        },
        
        // Templates
        templates: {
            title: 'Available Templates',
            subtitle: 'Choose the template that best fits your needs. The',
            subtitleHighlight: 'Basic',
            subtitleEnd: 'template is recommended for most users.',
            minimal: 'Minimal',
            minimalDesc: 'A very minimal template using only one stewbeet plugin.',
            minimalBestFor: 'Learning Beet basics',
            basic: 'Basic',
            basicDesc: 'A template with complete configuration but no coded features.',
            basicBestFor: 'Most users (recommended)',
            extensive: 'Extensive',
            extensiveDesc: 'A template with all the features of the framework, including all the plugins.',
            extensiveBestFor: 'Advanced users looking for examples',
            downloadZip: 'Download .zip',
            initCommand: 'Init via CLI',
            features: 'Features',
        },
        
        // Showcase
        showcase: {
            title: 'StewBeet Individual Plugins',
            subtitle: 'Over 20 plugins to automate every aspect of your datapack.',
            legend: 'Legend:',
            fullyDependent: 'Fully dependent',
            partlyDependent: 'Partly dependent',
            independent: 'Independent',
        },
        
        // Plugins Table
        pluginsTable: {
            category: 'Category',
            plugin: 'Plugin',
            description: 'Description',
            image: 'Image',
            dependency: 'Dependency',
            // Categories
            categoryCore: 'Core',
            categoryResourcePack: 'Resource Pack',
            categoryRecipes: 'Recipes',
            categoryCustomContent: 'Custom Content',
            categoryDocumentation: 'Documentation',
            categoryDatapack: 'Datapack',
            categoryFinalization: 'Finalization',
            categoryAutomation: 'Automation',
            categoryBuild: 'Build',
            // Plugins
            initializeDesc: 'Initializes the framework and sets up project metadata',
            verifyDefinitionsDesc: 'Validates the structure of definitions and checks consistency',
            soundsDesc: 'Processes sound files and generates sounds.json automatically',
            itemModelsDesc: 'Automatically generates item and block models',
            checkPowerOf2Desc: 'Validates that textures use power-of-2 resolutions',
            customRecipesDesc: 'Generates vanilla, smithed, furnace, and pulverizer recipes',
            customPaintingsDesc: 'Creates custom painting variants',
            ingameManualDesc: 'Generates an interactive in-game manual with documentation',
            loadingDesc: 'Sets up the loading system with versioning',
            customBlocksDesc: 'Implements placement, destruction, and interaction for custom blocks',
            lootTablesDesc: 'Generates loot tables and give-all functionality',
            sortersDesc: 'Generates sorting functions for NBT lists',
            customBlocksTickingDesc: 'Configures the ticking system for custom blocks',
            basicDatapackStructureDesc: 'Creates the timing structure (tick, second, minute)',
            dependenciesDesc: 'Manages external library dependencies',
            checkUnusedTexturesDesc: 'Identifies unused textures in the resource pack',
            langFileDesc: 'Automatically generates language files',
            headersDesc: 'Adds automatic headers to mcfunction files',
            scoreboardConstantsDesc: 'Detects scoreboard constant usages and generates initialization commands',
            archiveDesc: 'Creates zip archives of datapacks and resource packs',
            mergeSmithedWeldDesc: 'Merges datapacks and resource packs with libraries',
            copyToDestinationDesc: 'Copies generated packs to destination folders',
            computeSha1Desc: 'Computes SHA1 hashes for all zip files',
        },
        
        // Documentation Page
        documentation: {
            title: 'Documentation',
            subtitle: 'Learn how to use StewBeet',
            gettingStarted: 'Getting Started',
            gettingStartedDesc: 'Complete guide for beginners - installation, setup, and creating your first datapack',
            definitionsSetup: 'Definitions Setup',
            definitionsSetupDesc: 'Learn how to define custom items, blocks, and equipment configurations',
            writingToFiles: 'Writing to Files',
            writingToFilesDesc: 'Master file writing with static loading, native beet API, and StewBeet helper functions',
            beetConfig: 'Beet Configuration',
            beetConfigDesc: 'Complete reference for all beet.yml configuration options including StewBeet-specific settings',
            plugins: 'Available Plugins',
            pluginsSubtitle: 'Browse all available StewBeet plugins',
            searchPlaceholder: 'Search plugins...',
            filterAll: 'All',
            filterCore: 'Core',
            filterCompatibility: 'Compatibility',
            filterDatapack: 'Datapack',
            pluginName: 'Plugin',
            description: 'Description',
            noResults: 'No plugins found matching your search.',
        },
        
        // Markdown Page
        markdown: {
            back: 'Back',
            contents: 'Contents',
            viewOnGithub: 'View on GitHub',
            error: 'Error',
            loading: 'Loading...',
            noPlugin: 'No plugin specified. Please provide a "src" parameter.',
        },
        
        // Footer
        footer: {
            tagline: 'Powerful automation framework to create Minecraft datapacks effortlessly.',
            community: 'Community',
            resources: 'Resources',
            github: 'GitHub',
            discord: 'Discord',
            youtube: 'YouTube',
            pypiPackage: 'PyPI Package',
            planetMinecraft: 'PlanetMinecraft',
            reportBug: 'Report Bug',
            copyright: 'StewBeet by',
        },
    },
    
    fr: {
        // Navbar
        nav: {
            features: 'Fonctionnalités',
            installation: 'Installation',
            templates: 'Modèles',
            plugins: 'Plugins',
            documentation: 'Documentation',
            github: 'GitHub',
            language: 'Langue',
        },
        
        // Hero Section
        hero: {
            title: 'StewBeet',
            subtitle: 'Un puissant plugin Python pour Beet, boostant votre développement de datapacks Minecraft',
            getStarted: 'Commencer',
            viewDocs: 'Voir la documentation',
            scrollDown: 'Défiler pour explorer',            versionStable: 'Version Stable',
            automateTitle: 'Automatisez vos',
            minecraftDatapacks: 'Datapacks Minecraft',
            description: 'StewBeet est un framework',
            beet: 'Beet',
            descriptionContinued: 'fournissant une puissante automatisation pour les datapacks Minecraft. Adaptable à n\'importe quel workflow—utilisez uniquement les fonctionnalités dont vous avez besoin, ou exploitez la suite complète pour une génération de projet complète.',
            typeSafe: 'Définitions type-safe',
            autoGenerated: 'Ressources auto-générées',
            buildTime: 'Temps de Build',
            fast: 'Rapide',
            filesGenerated: 'Fichiers Générés',        },
        
        // What is StewBeet
        whatIs: {
            title: 'Qu\'est-ce que StewBeet ?',
            description: 'Un framework Beet qui révolutionne la création de datapacks Minecraft en automatisant tout ce qui est répétitif et chronophage.',
            problem: 'Le Problème',
            problemDesc: 'Créer un datapack nécessite d\'écrire manuellement des centaines de fichiers JSON, modèles, textures, fonctions...',
            solution: 'La Solution',
            solutionDesc: 'StewBeet automatise TOUT : génération de resource pack, modèles, blocs personnalisés, recettes, et bien plus !',
            result: 'Le Résultat',
            resultDesc: 'Concentrez-vous sur la création, pas sur les fichiers. Définissez vos objets et laissez StewBeet générer le reste.',
        },
        
        // Features
        features: {
            title: 'Automatisation',
            titleHighlight: 'Puissante',
            subtitle: 'StewBeet gère les parties répétitives de la création de datapacks pour que vous puissiez vous concentrer sur la mécanique.',
            integrations: 'Intégrations',
            // Individual features
            itemModelsTitle: 'Modèles d\'Objets Auto',
            itemModelsDesc: 'Génère automatiquement les modèles d\'objets et de blocs à partir des motifs de textures. Détecte les motifs cube, gâteau, orientable et plus. Reconnaît le suffixe _on pour créer des modèles alimentés/non-alimentés.',
            loadingTitle: 'Chargement Datapack',
            loadingDesc: 'Configure l\'infrastructure de timing avec les fonctions tick, seconde, minute. Inclut la vérification de version et la compatibilité LanternLoad.',
            lootTablesTitle: 'Tables de Butin & Give',
            lootTablesDesc: 'Tables de butin auto-générées pour chaque objet défini avec une fonction _give_all pratique pour les tests.',
            manualTitle: 'Manuel en Jeu',
            manualDesc: 'Manuel interactif généré automatiquement avec la documentation des objets, recettes de craft, et navigation cliquable.',
            langTitle: 'Fichiers Lang Auto',
            langDesc: 'Extrait automatiquement les composants de texte de votre code et génère les fichiers de traduction en_us.json.',
            customBlocksTitle: 'Blocs Personnalisés',
            customBlocksDesc: 'Système complet de blocs personnalisés avec placement, destruction, drops de minerais (fortune/silk touch), et intégration Smithed.',
        },
        
        // Installation
        installation: {
            title: 'Commencez en',
            titleHighlight: 'Secondes',
            step1: 'Installer Python',
            step1Desc: 'Assurez-vous que Python 3.14+ est installé',
            step2: 'Installer StewBeet',
            step2Desc: 'Obtenez le package via pip',
            step3: 'Initialiser le Projet',
            step3Desc: 'Choisissez un modèle pour commencer',
            step4: 'Compiler',
            step4Desc: 'Générez votre datapack',
        },
        
        // Templates
        templates: {
            title: 'Modèles Disponibles',
            subtitle: 'Choisissez le modèle qui correspond le mieux à vos besoins. Le modèle',
            subtitleHighlight: 'Basique',
            subtitleEnd: 'est recommandé pour la plupart des utilisateurs.',
            minimal: 'Minimal',
            minimalDesc: 'Un modèle très minimal utilisant un seul plugin stewbeet.',
            minimalBestFor: 'Apprendre les bases de Beet',
            basic: 'Basique',
            basicDesc: 'Un modèle avec une configuration complète mais sans fonctionnalités codées.',
            basicBestFor: 'La plupart des utilisateurs (recommandé)',
            extensive: 'Complet',
            extensiveDesc: 'Un modèle avec toutes les fonctionnalités du framework, incluant tous les plugins.',
            extensiveBestFor: 'Utilisateurs avancés cherchant des exemples',
            downloadZip: 'Télécharger .zip',
            initCommand: 'Init via CLI',
            features: 'Fonctionnalités',
        },
        
        // Showcase
        showcase: {
            title: 'Plugins Individuels StewBeet',
            subtitle: 'Plus de 20 plugins pour automatiser chaque aspect de votre datapack.',
            legend: 'Légende :',
            fullyDependent: 'Entièrement dépendant',
            partlyDependent: 'Partiellement dépendant',
            independent: 'Indépendant',
        },        
        // Plugins Table
        pluginsTable: {
            category: 'Catégorie',
            plugin: 'Plugin',
            description: 'Description',
            image: 'Image',
            dependency: 'Dépendance',
            // Categories
            categoryCore: 'Noyau',
            categoryResourcePack: 'Pack de Ressources',
            categoryRecipes: 'Recettes',
            categoryCustomContent: 'Contenu Personnalisé',
            categoryDocumentation: 'Documentation',
            categoryDatapack: 'Datapack',
            categoryFinalization: 'Finalisation',
            categoryAutomation: 'Automatisation',
            categoryBuild: 'Construction',
            // Plugins
            initializeDesc: 'Initialise le framework et configure les métadonnées du projet',
            verifyDefinitionsDesc: 'Valide la structure des définitions et vérifie la cohérence',
            soundsDesc: 'Traite les fichiers audio et génère sounds.json automatiquement',
            itemModelsDesc: 'Génère automatiquement les modèles d\'objets et de blocs',
            checkPowerOf2Desc: 'Valide que les textures utilisent des résolutions en puissance de 2',
            customRecipesDesc: 'Génère des recettes vanilla, smithed, furnace et pulverizer',
            customPaintingsDesc: 'Crée des variantes de peintures personnalisées',
            ingameManualDesc: 'Génère un manuel interactif en jeu avec documentation',
            loadingDesc: 'Configure le système de chargement avec versioning',
            customBlocksDesc: 'Implémente le placement, la destruction et l\'interaction pour les blocs personnalisés',
            lootTablesDesc: 'Génère les tables de butin et la fonctionnalité give-all',
            sortersDesc: 'Génère des fonctions de tri pour les listes NBT',
            customBlocksTickingDesc: 'Configure le système de ticking pour les blocs personnalisés',
            basicDatapackStructureDesc: 'Crée la structure temporelle (tick, seconde, minute)',
            dependenciesDesc: 'Gère les dépendances de bibliothèques externes',
            checkUnusedTexturesDesc: 'Identifie les textures inutilisées dans le pack de ressources',
            langFileDesc: 'Génère automatiquement les fichiers de langue',
            headersDesc: 'Ajoute des en-têtes automatiques aux fichiers mcfunction',
            scoreboardConstantsDesc: 'Détecte les constantes de scoreboard et génère leurs commandes d\'initialisation',
            archiveDesc: 'Crée des archives zip des datapacks et packs de ressources',
            mergeSmithedWeldDesc: 'Fusionne les datapacks et packs de ressources avec les bibliothèques',
            copyToDestinationDesc: 'Copie les packs générés vers les dossiers de destination',
            computeSha1Desc: 'Calcule les hachages SHA1 pour tous les fichiers zip',
        },        
        // Documentation Page
        documentation: {
            title: 'Documentation',
            subtitle: 'Apprenez à utiliser StewBeet',
            gettingStarted: 'Démarrage',
            gettingStartedDesc: 'Guide complet pour débutants - installation, configuration et création de votre premier datapack',
            definitionsSetup: 'Configuration des Définitions',
            definitionsSetupDesc: 'Apprenez à définir des objets, blocs et configurations d\'équipement personnalisés',
            writingToFiles: 'Écriture dans les Fichiers',
            writingToFilesDesc: 'Maîtrisez l\'écriture de fichiers avec le chargement statique, l\'API native de beet et les fonctions d\'aide de StewBeet',
            beetConfig: 'Configuration Beet',
            beetConfigDesc: 'Référence complète pour toutes les options de configuration beet.yml incluant les paramètres spécifiques à StewBeet',
            plugins: 'Plugins Disponibles',
            pluginsSubtitle: 'Parcourir tous les plugins StewBeet disponibles',
            searchPlaceholder: 'Rechercher des plugins...',
            filterAll: 'Tous',
            filterCore: 'Core',
            filterCompatibility: 'Compatibilité',
            filterDatapack: 'Datapack',
            pluginName: 'Plugin',
            description: 'Description',
            noResults: 'Aucun plugin trouvé correspondant à votre recherche.',
        },
        
        // Markdown Page
        markdown: {
            back: 'Retour',
            contents: 'Contenu',
            viewOnGithub: 'Voir sur GitHub',
            error: 'Erreur',
            loading: 'Chargement...',
            noPlugin: 'Aucun plugin spécifié. Veuillez fournir un paramètre "src".',
        },
        
        // Footer
        footer: {
            tagline: 'Framework d\'automatisation puissant pour créer des datapacks Minecraft sans effort.',
            community: 'Communauté',
            resources: 'Ressources',
            github: 'GitHub',
            discord: 'Discord',
            youtube: 'YouTube',
            pypiPackage: 'Package PyPI',
            planetMinecraft: 'PlanetMinecraft',
            reportBug: 'Signaler un Bug',
            copyright: 'StewBeet par',
        },
    },
} as const;

export type TranslationKeys = typeof translations.en;
export type NestedKeyOf<T> = T extends object
    ? {
          [K in keyof T]: K extends string
              ? T[K] extends object
                  ? `${K}.${NestedKeyOf<T[K]>}`
                  : K
              : never;
      }[keyof T]
    : never;

export function getTranslation(lang: Language, key: string): string {
    const keys = key.split('.');
    let value: any = translations[lang];
    
    for (const k of keys) {
        value = value?.[k];
        if (value === undefined) {
            console.warn(`Translation key not found: ${key} for language: ${lang}`);
            return key;
        }
    }
    
    return value;
}
