
# Imports
import hashlib
import marshal
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

import stouputils as stp
from beet import Context, JsonFile
from stouputils.typing import JsonDict

# Model serialization cache
MODEL_CACHE_NAME: str = "stewbeet_model_encoder"
""" Name of the beet cache holding serialized models. """

MODEL_CACHE_MAX_AGE: timedelta = timedelta(days=7)
""" Entries untouched for longer than this are dropped at the start of a build. """

MODEL_CACHE_MIN_SIZE: int = 8192
""" Contents whose marshalled size is below this are serialized directly instead of cached.

Caching costs a directory lookup, a file read and a timestamp update, which together run to roughly
0.2ms per entry; serializing runs at roughly 55ms per megabyte. Below a few kilobytes the cache is
therefore slower than simply doing the work, and on a pack with thousands of tiny json files that
overhead adds up to more than it saves. """


class ModelSerializationCache:
	""" Content-addressed, cross-build cache of serialized models.

	Serializing models dominates build time on packs that generate many variants of the same
	geometry: the ``elements`` array is by far the biggest part of a model file, and packs with
	camouflages / powered states / zoom levels emit the same geometry hundreds of times.

	Entries are keyed on a hash of the model content itself, not on where it came from. That is what
	makes the cache safe to keep between builds: any change that alters a generated model — editing
	the source geometry, changing how models are built, upgrading StewBeet — changes the hash and
	misses the cache. There is no invalidation rule to keep in sync, and no way to serve a model that
	was generated by code that no longer exists.

	The hash covers the encoder settings and the versions of everything involved in producing the
	text (Python, ``marshal``, ``stouputils``), since those decide the formatting rather than the
	content. ``marshal`` is used to turn the model into bytes because it is a C serializer for exactly
	these primitive types and runs several times faster than ``json.dumps``; its output is stable
	within a given interpreter version, which is why that version is part of the key.

	Attributes:
		directory (Path): Directory holding one file per cached model.
		hits      (int):  Number of models served from the cache during this build.
		misses    (int):  Number of models serialized during this build.
	"""

	def __init__(self, directory: Path) -> None:
		""" Prepare the cache directory and evict stale entries.

		Args:
			directory (Path): Directory to store cached models in (created if missing).
		"""
		self.directory: Path = directory
		self.directory.mkdir(parents=True, exist_ok=True)
		self.hits: int = 0
		self.misses: int = 0

		# Formatting-affecting versions, mixed into every key (see the class docstring)
		self.salt: bytes = "|".join((
			f"py{sys.version_info[0]}.{sys.version_info[1]}",
			f"marshal{marshal.version}",
			f"stouputils{getattr(stp, '__version__', 'unknown')}",
		)).encode()

		self.evict_old_entries()

	def evict_old_entries(self) -> None:
		""" Delete entries that were not used recently, so the cache cannot grow without bound. """
		deadline: float = (datetime.now() - MODEL_CACHE_MAX_AGE).timestamp()
		# Also sweep leftover temporaries: a build killed mid-write leaves one behind, and nothing
		# else would ever remove it since only completed entries are looked up.
		for entry in (*self.directory.glob("*.json"), *self.directory.glob("*.tmp")):
			try:
				if entry.stat().st_mtime < deadline:
					entry.unlink()
			except OSError:
				pass  # Concurrent build cleaning the same entry, or a locked file: not worth failing over

	def compute_key(self, data: JsonDict, max_level: int, indent: str) -> str | None:
		""" Hash a model into a cache key.

		Args:
			data      (JsonDict): The model content.
			max_level (int):      The depth of indentation the model will be serialized with.
			indent    (str):      The indentation character.

		Returns:
			str | None: The key, or None when the content should not be cached at all: either it holds
				values ``marshal`` cannot serialize, or it is too small to be worth caching.
		"""
		try:
			payload: bytes = marshal.dumps(data)
		except ValueError:
			return None  # Unmarshalable value: fall back to serializing every time

		# Too small for the cache to pay for itself (see MODEL_CACHE_MIN_SIZE)
		if len(payload) < MODEL_CACHE_MIN_SIZE:
			return None

		digest = hashlib.blake2b(digest_size=16)
		digest.update(self.salt)
		digest.update(f"|max_level{max_level}|indent{indent}|".encode())
		digest.update(payload)
		return digest.hexdigest()

	def encode(self, data: JsonDict, max_level: int = 4, indent: str = '\t') -> str:
		""" Serialize a model, reusing the stored text when this exact model was serialized before.

		Args:
			data      (JsonDict): The model content to serialize.
			max_level (int):      The depth of indentation to stop at (see ``stouputils.json_dump``).
			indent    (str):      The indentation character.

		Returns:
			str: The serialized model, byte-for-byte identical to ``stp.json_dump(data, max_level)``.
		"""
		key: str | None = self.compute_key(data, max_level, indent)
		if key is None:
			return stp.json_dump(data, max_level=max_level, indent=indent)
		entry: Path = self.directory / f"{key}.json"

		# Cache hit: the stored text was produced by this exact model and these exact settings
		try:
			content: str = entry.read_text(encoding="utf-8")
			self.hits += 1
			os.utime(entry, None)  # Mark as used so eviction keeps the working set
			return content
		except OSError:
			pass

		# Cache miss: serialize, then store for the next build
		self.misses += 1
		content = stp.json_dump(data, max_level=max_level, indent=indent)

		# Write through a temporary file: a build interrupted mid-write must not leave a truncated
		# entry behind, since the next build would read it back as if it were complete.
		try:
			temporary: Path = entry.with_suffix(f".{os.getpid()}.tmp")
			temporary.write_text(content, encoding="utf-8")
			os.replace(temporary, entry)
		except OSError:
			pass  # Cache is an optimization: failing to store must never fail the build

		return content


active_model_cache: ModelSerializationCache | None = None
""" Cache installed for the current build by the item_models plugin. None disables caching.

Deliberately not upper-cased: it is rebound on every build rather than being a constant. """


def setup_model_cache(ctx: Context) -> ModelSerializationCache:
	""" Create the model serialization cache for this build and make it the active one.

	Args:
		ctx (Context): The beet context, used for its cache directory.

	Returns:
		ModelSerializationCache: The cache that was installed.
	"""
	global active_model_cache
	active_model_cache = ModelSerializationCache(ctx.cache[MODEL_CACHE_NAME].directory)
	return active_model_cache


# Set the caching model encoder for a Model object
def set_model_encoder[JsonFileT: JsonFile](obj: JsonFileT, max_level: int = 4, indent: str = '\t') -> JsonFileT:
	""" Set the encoder of the given model to the cached serializer.

	Falls back to plain ``json_dump`` when no cache is active, so models can still be encoded outside
	of a build (tests, direct library use).

	Args:
		obj       (JsonFile):  The model to set the encoder for.
		max_level (int):       The maximum level of the JSON dump.
		indent    (str):       The indentation character (default: '\\t')
	Returns:
		JsonFile: The object with the encoder set
	"""
	# Reads the global at call time, so models encoded after a build installs its cache use it
	def encoder(data: JsonDict) -> str:
		if active_model_cache is None:
			return stp.json_dump(data, max_level=max_level, indent=indent)
		return active_model_cache.encode(data, max_level=max_level, indent=indent)

	obj.encoder = encoder
	return obj

